language: shell
os: windows
before_script:
- export JAVA_HOME=${JAVA_HOME:-/c/jdk}
- export PATH=${JAVA_HOME}/bin:${PATH}
- choco install ojdkbuild8
- choco install maven
- powershell refreshenv
script:
- ls
- pwd
- cd ../../../ProgramData/chocolatey/lib/maven/bin
- mvn install test -B -V